version: "3"
services:
  rest-number:
    image: "dng-p/rest-book:0.01"
    ports:
      - "8701:8701"
  rest-book:
    image: "dng-p/rest-number:0.01"
    ports:
      - "8702:8702"
    environment:
      - NUMBER_PROXY_MP_REST_URL=http://rest-number:8701